-- 한국공학대학교 기술지주회사 홈페이지 — 초기 스키마
-- 게시글 / 기업(자회사·투자기업) / 문의 / 팝업 + RLS + 파일 저장소

create extension if not exists pgcrypto;

-- ───────────────── 게시글 (공지사항·언론보도·자료실·Q&A) ─────────────────
create table if not exists public.posts (
    id          bigint generated by default as identity primary key,
    category    text not null check (category in ('notice', 'press', 'resources', 'faq')),
    title       text not null,
    date        text not null,                 -- 표시용 'YYYY.MM.DD'
    author      text default '관리자',
    views       integer not null default 0,
    content     text,
    is_new      boolean not null default false,
    file_type   text,
    file_name   text,
    file_url    text,
    files       jsonb not null default '[]'::jsonb,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);
create index if not exists posts_category_date_idx on public.posts (category, date desc, id desc);

-- ───────────────── 기업 (자회사 / 투자기업) ─────────────────
create table if not exists public.companies (
    id            text primary key,
    name          text not null,
    ceo           text,
    founded_date  text,
    business      text,
    room          text,
    move_in_date  text,
    homepage      text,
    note          text,
    is_tips       boolean not null default false,
    category      text not null check (category in ('subsidiary', 'portfolio')),
    logo          text,
    bg_image      text,
    short_desc    text,
    sort_order    integer not null default 0,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

-- ───────────────── 문의 (지원하기) ─────────────────
create table if not exists public.inquiries (
    id            bigint generated by default as identity primary key,
    inquiry_type  text,
    name          text not null,
    contact       text not null,
    email         text not null,
    company_name  text,
    content       text not null,
    date          text not null,               -- 'YYYY-MM-DD'
    status        text not null default '대기' check (status in ('대기', '완료')),
    created_at    timestamptz not null default now()
);

-- ───────────────── 팝업 ─────────────────
create table if not exists public.popups (
    id          bigint generated by default as identity primary key,
    title       text not null,
    image       text,
    content     text,
    link        text,
    start_date  text not null,
    end_date    text not null,
    is_visible  boolean not null default true,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- updated_at 자동 갱신
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end $$;

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at before update on public.posts
    for each row execute function public.set_updated_at();
drop trigger if exists companies_set_updated_at on public.companies;
create trigger companies_set_updated_at before update on public.companies
    for each row execute function public.set_updated_at();
drop trigger if exists popups_set_updated_at on public.popups;
create trigger popups_set_updated_at before update on public.popups
    for each row execute function public.set_updated_at();

-- 조회수 증가 (비로그인 방문자도 호출 가능, 조회수 컬럼만 +1)
create or replace function public.increment_post_views(post_id bigint) returns void
language sql security definer set search_path = public as $$
    update public.posts set views = views + 1 where id = post_id;
$$;
grant execute on function public.increment_post_views(bigint) to anon, authenticated;

-- ───────────────── RLS ─────────────────
alter table public.posts     enable row level security;
alter table public.companies enable row level security;
alter table public.inquiries enable row level security;
alter table public.popups    enable row level security;

-- 공개 읽기
drop policy if exists "posts public read" on public.posts;
create policy "posts public read" on public.posts for select to anon, authenticated using (true);
drop policy if exists "companies public read" on public.companies;
create policy "companies public read" on public.companies for select to anon, authenticated using (true);
drop policy if exists "popups public read" on public.popups;
create policy "popups public read" on public.popups for select to anon, authenticated using (true);

-- 관리자(로그인 사용자) 쓰기
drop policy if exists "posts admin write" on public.posts;
create policy "posts admin write" on public.posts for all to authenticated using (true) with check (true);
drop policy if exists "companies admin write" on public.companies;
create policy "companies admin write" on public.companies for all to authenticated using (true) with check (true);
drop policy if exists "popups admin write" on public.popups;
create policy "popups admin write" on public.popups for all to authenticated using (true) with check (true);

-- 문의: 누구나 접수, 관리자만 조회/수정/삭제
drop policy if exists "inquiries public insert" on public.inquiries;
create policy "inquiries public insert" on public.inquiries for insert to anon, authenticated with check (true);
drop policy if exists "inquiries admin read" on public.inquiries;
create policy "inquiries admin read" on public.inquiries for select to authenticated using (true);
drop policy if exists "inquiries admin update" on public.inquiries;
create policy "inquiries admin update" on public.inquiries for update to authenticated using (true) with check (true);
drop policy if exists "inquiries admin delete" on public.inquiries;
create policy "inquiries admin delete" on public.inquiries for delete to authenticated using (true);

-- ───────────────── 파일 저장소 (첨부파일·로고·팝업 이미지) ─────────────────
insert into storage.buckets (id, name, public, file_size_limit)
values ('uploads', 'uploads', true, 52428800)
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit;

drop policy if exists "uploads public read" on storage.objects;
create policy "uploads public read" on storage.objects for select to anon, authenticated using (bucket_id = 'uploads');
drop policy if exists "uploads admin insert" on storage.objects;
create policy "uploads admin insert" on storage.objects for insert to authenticated with check (bucket_id = 'uploads');
drop policy if exists "uploads admin update" on storage.objects;
create policy "uploads admin update" on storage.objects for update to authenticated using (bucket_id = 'uploads');
drop policy if exists "uploads admin delete" on storage.objects;
create policy "uploads admin delete" on storage.objects for delete to authenticated using (bucket_id = 'uploads');
